#include <assert.h>
#include <errno.h>
#include <fcntl.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>

#include "alt_generalpurpose_io.h"
#include "hwlib.h"
#include "socal/alt_gpio.h"
#include "socal/hps.h"
#include "socal/socal.h"
#include "hps_linux.h"

/* header file generated by sopc-create-header from Quartus/QSys SoC file */
#include "../hps_soc_system.h"

void open_physical_memory_device() {
    fd_dev_mem = open("/dev/mem", O_RDWR | O_SYNC);
    if(fd_dev_mem  == -1) {
        printf("ERROR: could not open \"/dev/mem\".\n");
        printf("    errno = %s\n", strerror(errno));
        exit(EXIT_FAILURE);
    }
}

void close_physical_memory_device() {
    close(fd_dev_mem);
}

void mmap_hps_peripherals() {
    hps_gpio = mmap(NULL, hps_gpio_span, PROT_READ | PROT_WRITE, MAP_SHARED, fd_dev_mem, hps_gpio_ofst);
    if (hps_gpio == MAP_FAILED) {
        printf("Error: hps_gpio mmap() failed.\n");
        printf("    errno = %s\n", strerror(errno));
        close(fd_dev_mem);
        exit(EXIT_FAILURE);
    }
}

void munmap_hps_peripherals() {
    if (munmap(hps_gpio, hps_gpio_span) != 0) {
        printf("Error: hps_gpio munmap() failed\n");
        printf("    errno = %s\n", strerror(errno));
        close(fd_dev_mem);
        exit(EXIT_FAILURE);
    }

    hps_gpio = NULL;
}

void mmap_hps_RAMs() {
	RAMDest_UART0_RX = mmap(NULL, RAMDEST_UART0_RX_END - RAMDEST_UART0_RX_START + 1, PROT_READ | PROT_WRITE, MAP_SHARED, fd_dev_mem, RAMDEST_UART0_RX_START);
    if (RAMDest_UART0_RX == MAP_FAILED) {
        printf("Error: RAMDest_UART0 mmap() failed.\n");
        printf("    errno = %s\n", strerror(errno));
        close(fd_dev_mem);
        exit(EXIT_FAILURE);
    }

	RAMDest_UART1_RX = mmap(NULL, RAMDEST_UART1_RX_END-RAMDEST_UART1_RX_START+1, PROT_READ | PROT_WRITE, MAP_SHARED, fd_dev_mem, RAMDEST_UART1_RX_START);
    if (RAMDest_UART1_RX == MAP_FAILED) {
        printf("Error: RAMDest_UART1 mmap() failed.\n");
        printf("    errno = %s\n", strerror(errno));
        close(fd_dev_mem);
        exit(EXIT_FAILURE);
    }

	RAMDest_UART2_RX = mmap(NULL, RAMDEST_UART2_RX_END-RAMDEST_UART2_RX_START+1, PROT_READ | PROT_WRITE, MAP_SHARED, fd_dev_mem, RAMDEST_UART2_RX_START);
    if (RAMDest_UART2_RX == MAP_FAILED) {
        printf("Error: RAMDest_UART2 mmap() failed.\n");
        printf("    errno = %s\n", strerror(errno));
        close(fd_dev_mem);
        exit(EXIT_FAILURE);
    }

	RAMDest_UART3_RX = mmap(NULL, RAMDEST_UART3_RX_END-RAMDEST_UART3_RX_START+1, PROT_READ | PROT_WRITE, MAP_SHARED, fd_dev_mem, RAMDEST_UART3_RX_START);
    if (RAMDest_UART3_RX == MAP_FAILED) {
        printf("Error: RAMDest_UART3 mmap() failed.\n");
        printf("    errno = %s\n", strerror(errno));
        close(fd_dev_mem);
        exit(EXIT_FAILURE);
    }

	RAMDest_UART4_RX = mmap(NULL, RAMDEST_UART4_RX_END-RAMDEST_UART4_RX_START+1, PROT_READ | PROT_WRITE, MAP_SHARED, fd_dev_mem, RAMDEST_UART4_RX_START);
    if (RAMDest_UART4_RX == MAP_FAILED) {
        printf("Error: RAMDest_UART4 mmap() failed.\n");
        printf("    errno = %s\n", strerror(errno));
        close(fd_dev_mem);
        exit(EXIT_FAILURE);
    }

	RAMDest_UART5_RX = mmap(NULL, RAMDEST_UART5_RX_END-RAMDEST_UART5_RX_START+1, PROT_READ | PROT_WRITE, MAP_SHARED, fd_dev_mem, RAMDEST_UART5_RX_START);
    if (RAMDest_UART5_RX == MAP_FAILED) {
        printf("Error: RAMDest_UART5 mmap() failed.\n");
        printf("    errno = %s\n", strerror(errno));
        close(fd_dev_mem);
        exit(EXIT_FAILURE);
    }

    RAMDest_UART_Info = mmap(NULL, 128, PROT_READ | PROT_WRITE, MAP_SHARED, fd_dev_mem, RAMDEST_UART_INFO);
    if (RAMDest_UART_Info == MAP_FAILED) {
        printf("Error: RAMDest_UART_Info mmap() failed.\n");
        printf("    errno = %s\n", strerror(errno));
        close(fd_dev_mem);
        exit(EXIT_FAILURE);
    }
}

void munmap_hps_RAMs() {
    if (munmap(RAMDest_UART0_RX, RAMDEST_UART0_RX_END - RAMDEST_UART0_RX_START + 1) != 0) {
        printf("Error: RAMDest_UART0 munmap() failed\n");
        printf("    errno = %s\n", strerror(errno));
        close(fd_dev_mem);
        exit(EXIT_FAILURE);
    }

    if (munmap(RAMDest_UART1_RX, RAMDEST_UART1_RX_END-RAMDEST_UART1_RX_START+1) != 0) {
        printf("Error: RAMDest_UART1 munmap() failed\n");
        printf("    errno = %s\n", strerror(errno));
        close(fd_dev_mem);
        exit(EXIT_FAILURE);
    }

    if (munmap(RAMDest_UART2_RX, RAMDEST_UART2_RX_END-RAMDEST_UART2_RX_START+1) != 0) {
        printf("Error: RAMDest_UART2 munmap() failed\n");
        printf("    errno = %s\n", strerror(errno));
        close(fd_dev_mem);
        exit(EXIT_FAILURE);
    }

    if (munmap(RAMDest_UART3_RX, RAMDEST_UART3_RX_END-RAMDEST_UART3_RX_START+1) != 0) {
        printf("Error: RAMDest_UART3 munmap() failed\n");
        printf("    errno = %s\n", strerror(errno));
        close(fd_dev_mem);
        exit(EXIT_FAILURE);
    }

    if (munmap(RAMDest_UART4_RX, RAMDEST_UART4_RX_END-RAMDEST_UART4_RX_START+1) != 0) {
        printf("Error: RAMDest_UART4 munmap() failed\n");
        printf("    errno = %s\n", strerror(errno));
        close(fd_dev_mem);
        exit(EXIT_FAILURE);
    }

    if (munmap(RAMDest_UART5_RX, RAMDEST_UART5_RX_END-RAMDEST_UART5_RX_START+1) != 0) {
        printf("Error: RAMDest_UART5 munmap() failed\n");
        printf("    errno = %s\n", strerror(errno));
        close(fd_dev_mem);
        exit(EXIT_FAILURE);
    }

    if (munmap(RAMDest_UART_Info, 128) != 0) {
        printf("Error: RAMDest_UART_Info munmap() failed\n");
        printf("    errno = %s\n", strerror(errno));
        close(fd_dev_mem);
        exit(EXIT_FAILURE);
    }

    RAMDest_UART0_RX = NULL;
    RAMDest_UART1_RX = NULL;
    RAMDest_UART2_RX = NULL;
    RAMDest_UART3_RX = NULL;
    RAMDest_UART4_RX = NULL;
    RAMDest_UART5_RX = NULL;

    RAMDest_UART_Info = NULL;
}


void mmap_fpga_peripherals() {

    h2f_lw_axi_master = mmap(NULL, h2f_lw_axi_master_span, PROT_READ | PROT_WRITE, MAP_SHARED, fd_dev_mem, h2f_lw_axi_master_ofst);
    if (h2f_lw_axi_master == MAP_FAILED) {
        printf("Error: h2f_lw_axi_master mmap() failed.\n");
        printf("    errno = %s\n", strerror(errno));
        close(fd_dev_mem);
        exit(EXIT_FAILURE);
    }

    fpga_leds = h2f_lw_axi_master + HPS_FPGA_LEDS_BASE;
}

void munmap_fpga_peripherals() {
    if (munmap(h2f_lw_axi_master, h2f_lw_axi_master_span) != 0) {
        printf("Error: h2f_lw_axi_master munmap() failed\n");
        printf("    errno = %s\n", strerror(errno));
        close(fd_dev_mem);
        exit(EXIT_FAILURE);
    }

    h2f_lw_axi_master = NULL;
    fpga_leds         = NULL;
}

void mmap_peripherals() {
    mmap_hps_peripherals();
    mmap_fpga_peripherals();
    mmap_hps_RAMs();
}

void munmap_peripherals() {
    munmap_hps_peripherals();
    munmap_fpga_peripherals();
    munmap_hps_RAMs();
}

void setup_hps_gpio() {
    // Initialize the HPS PIO controller:
    //     Set the direction of the HPS_LED GPIO bit to "output"
    //     Set the direction of the HPS_KEY_N GPIO bit to "input"
    void *hps_gpio_direction = ALT_GPIO_SWPORTA_DDR_ADDR(hps_gpio);
    alt_setbits_word(hps_gpio_direction, ALT_GPIO_PIN_OUTPUT << HPS_LED_PORT_BIT);
    alt_setbits_word(hps_gpio_direction, ALT_GPIO_PIN_INPUT << HPS_KEY_N_PORT_BIT);
}

bool read_hps_key() {
    void *hps_gpio_port = ALT_GPIO_EXT_PORTA_ADDR(hps_gpio);
    uint32_t hps_gpio_input = alt_read_word(hps_gpio_port) & HPS_KEY_N_MASK;
    // HPS_KEY_N is active-low
    return (~hps_gpio_input & HPS_KEY_N_MASK);
}

void toggle_hps_led() {
    void *hps_gpio_data = ALT_GPIO_SWPORTA_DR_ADDR(hps_gpio);
	uint32_t hps_led_value = alt_read_word(hps_gpio_data);
	hps_led_value >>= HPS_LED_PORT_BIT;
	hps_led_value = !hps_led_value;
	hps_led_value <<= HPS_LED_PORT_BIT;
	alt_replbits_word(hps_gpio_data, HPS_LED_MASK, hps_led_value);
}

void setup_fpga_leds() {
	printf("setup leds\n");
    alt_write_word(fpga_leds, 0x0001);
}

void toggle_fpga_leds() {
	uint32_t leds = alt_read_word(fpga_leds);
	leds = ~leds;
	alt_write_word(fpga_leds, leds);
}

void clear_leds() {
	printf("clear leds\n");
    alt_write_word(fpga_leds, 0x0000);
}

void set_leds() {
	printf("set leds\n");
    alt_write_word(fpga_leds, 0x0002);
}


typedef struct {
	uint32_t* RXBaseAddress[6];
	uint32_t RXFrameSize[6];
	uint32_t* RXNextFrameAddress[6];
} UART_info;

void* RXTransferFrameAddress[6];


int main() {
	int i,j;
    printf("DE0-Nano-SoC Sniffer HPS-side\n");

    open_physical_memory_device();
    mmap_peripherals();

    setup_hps_gpio();
    setup_fpga_leds();

    UART_info* info = RAMDest_UART_Info;

    // Initially, point to wherever the RX buffer FPGA pointer is
    // (i.e. disregard frames thay may have arrived in the buffer before this program is executed)
	for (i=0;i<6;i++)
	{
		RXTransferFrameAddress[i] = info->RXNextFrameAddress[i];
	}

    while (true) {
    	toggle_fpga_leds();
        usleep(5*ALT_MICROSECS_IN_A_SEC);

        for (i=0;i<6;i++)
		{
        	if (RXTransferFrameAddress[i] != info->RXNextFrameAddress[i])
        	{
        		printf("Got frames on channel %d\n", i);
        		// Flush all pending messages
        		while( RXTransferFrameAddress[i] != info->RXNextFrameAddress[i])
        		{
            		// TODO: push frame to Ethernet
        			printf("pushed one frame from channel %d\n", i);

        			RXTransferFrameAddress[i] += info->RXFrameSize[i];
        			printf("UART%d: RXTransferFrameAddress=0x%p\n", i, RXTransferFrameAddress[i]);
        		}
        	}

		}


/*
		for (i=0;i<6;i++)
		{
			printf("UART%d: BaseAddress=0x%p\n", i, info->RXBaseAddress[i]);
			printf("UART%d: FrameSize=%d\n", i, info->RXFrameSize[i]);
			printf("UART%d: NextFrameAddress=0x%p\n", i, info->RXNextFrameAddress[i]);
		}

    	uint32_t * addr;

    	for (j=0;j<16;j++)
    	{
    		addr = (uint32_t*)(RAMDest_UART0_RX + j*4096);

			printf("UART0_RX[%d] = ", j);
			for (i=0;i<8;i++)
			{
				printf("%08X ", *addr);
				addr++;
			}
			printf("\n");
    	}
		printf("\n");
*/

    }

    munmap_peripherals();
    close_physical_memory_device();

    return 0;
}
