/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'nios2_gen2_1' in SOPC Builder design 'soc_system'
 * SOPC Builder design path: /home/etabli/DE0_Nano_SoC_Sniffer/hw/quartus/soc_system.sopcinfo
 *
 * Generated: Sat Dec 08 19:52:10 CET 2018
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_gen2"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x00010820
#define ALT_CPU_CPU_ARCH_NIOS2_R1
#define ALT_CPU_CPU_FREQ 50000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "tiny"
#define ALT_CPU_DATA_ADDR_WIDTH 0x12
#define ALT_CPU_DCACHE_LINE_SIZE 0
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_DCACHE_SIZE 0
#define ALT_CPU_EXCEPTION_ADDR 0x00020020
#define ALT_CPU_FLASH_ACCELERATOR_LINES 0
#define ALT_CPU_FLASH_ACCELERATOR_LINE_SIZE 0
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 50000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 0
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 0
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_ICACHE_SIZE 0
#define ALT_CPU_INST_ADDR_WIDTH 0x12
#define ALT_CPU_NAME "nios2_gen2_1"
#define ALT_CPU_OCI_VERSION 1
#define ALT_CPU_RESET_ADDR 0x00020000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x00010820
#define NIOS2_CPU_ARCH_NIOS2_R1
#define NIOS2_CPU_FREQ 50000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "tiny"
#define NIOS2_DATA_ADDR_WIDTH 0x12
#define NIOS2_DCACHE_LINE_SIZE 0
#define NIOS2_DCACHE_LINE_SIZE_LOG2 0
#define NIOS2_DCACHE_SIZE 0
#define NIOS2_EXCEPTION_ADDR 0x00020020
#define NIOS2_FLASH_ACCELERATOR_LINES 0
#define NIOS2_FLASH_ACCELERATOR_LINE_SIZE 0
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 0
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 0
#define NIOS2_ICACHE_LINE_SIZE_LOG2 0
#define NIOS2_ICACHE_SIZE 0
#define NIOS2_INST_ADDR_WIDTH 0x12
#define NIOS2_OCI_VERSION 1
#define NIOS2_RESET_ADDR 0x00020000


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_PIO
#define __ALTERA_AVALON_TIMER
#define __ALTERA_NIOS2_GEN2
#define __FIFOED_AVALON_UART


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Cyclone V"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/null"
#define ALT_STDERR_BASE 0x0
#define ALT_STDERR_DEV null
#define ALT_STDERR_TYPE ""
#define ALT_STDIN "/dev/null"
#define ALT_STDIN_BASE 0x0
#define ALT_STDIN_DEV null
#define ALT_STDIN_TYPE ""
#define ALT_STDOUT "/dev/null"
#define ALT_STDOUT_BASE 0x0
#define ALT_STDOUT_DEV null
#define ALT_STDOUT_TYPE ""
#define ALT_SYSTEM_NAME "soc_system"


/*
 * fifoed_avalon_uart_1 configuration
 *
 */

#define ALT_MODULE_CLASS_fifoed_avalon_uart_1 fifoed_avalon_uart
#define FIFOED_AVALON_UART_1_ADD_ERROR_BITS 0
#define FIFOED_AVALON_UART_1_BASE 0x11040
#define FIFOED_AVALON_UART_1_BAUD 1000000
#define FIFOED_AVALON_UART_1_DATA_BITS 8
#define FIFOED_AVALON_UART_1_FIFO_EXPORT_USED 0
#define FIFOED_AVALON_UART_1_FIXED_BAUD 1
#define FIFOED_AVALON_UART_1_FREQ 50000000
#define FIFOED_AVALON_UART_1_GAP_VALUE 2
#define FIFOED_AVALON_UART_1_IRQ 0
#define FIFOED_AVALON_UART_1_IRQ_INTERRUPT_CONTROLLER_ID 0
#define FIFOED_AVALON_UART_1_NAME "/dev/fifoed_avalon_uart_1"
#define FIFOED_AVALON_UART_1_PARITY 'N'
#define FIFOED_AVALON_UART_1_PASS_ERROR_BITS 0
#define FIFOED_AVALON_UART_1_RX_FIFO_LE 0
#define FIFOED_AVALON_UART_1_RX_FIFO_SIZE 128
#define FIFOED_AVALON_UART_1_RX_IRQ_THRESHOLD 1
#define FIFOED_AVALON_UART_1_SIM_CHAR_STREAM ""
#define FIFOED_AVALON_UART_1_SIM_TRUE_BAUD 0
#define FIFOED_AVALON_UART_1_SPAN 64
#define FIFOED_AVALON_UART_1_STOP_BITS 1
#define FIFOED_AVALON_UART_1_SYNC_REG_DEPTH 2
#define FIFOED_AVALON_UART_1_TIMEOUT_VALUE 4
#define FIFOED_AVALON_UART_1_TIMESTAMP_WIDTH 8
#define FIFOED_AVALON_UART_1_TRANSMIT_PIN 0
#define FIFOED_AVALON_UART_1_TX_FIFO_LE 0
#define FIFOED_AVALON_UART_1_TX_FIFO_SIZE 8
#define FIFOED_AVALON_UART_1_TX_IRQ_THRESHOLD 1
#define FIFOED_AVALON_UART_1_TYPE "fifoed_avalon_uart"
#define FIFOED_AVALON_UART_1_UHW_CTS 0
#define FIFOED_AVALON_UART_1_USE_CTS_RTS 0
#define FIFOED_AVALON_UART_1_USE_EOP_REGISTER 0
#define FIFOED_AVALON_UART_1_USE_EXT_TIMESTAMP 0
#define FIFOED_AVALON_UART_1_USE_GAP_DETECTION 1
#define FIFOED_AVALON_UART_1_USE_RX_FIFO 1
#define FIFOED_AVALON_UART_1_USE_RX_TIMEOUT 0
#define FIFOED_AVALON_UART_1_USE_STATUS_BIT_CLEAR 0
#define FIFOED_AVALON_UART_1_USE_TIMESTAMP 0
#define FIFOED_AVALON_UART_1_USE_TX_FIFO 0


/*
 * fifoed_avalon_uart_1_txenable configuration
 *
 */

#define ALT_MODULE_CLASS_fifoed_avalon_uart_1_txenable altera_avalon_pio
#define FIFOED_AVALON_UART_1_TXENABLE_BASE 0x11090
#define FIFOED_AVALON_UART_1_TXENABLE_BIT_CLEARING_EDGE_REGISTER 0
#define FIFOED_AVALON_UART_1_TXENABLE_BIT_MODIFYING_OUTPUT_REGISTER 0
#define FIFOED_AVALON_UART_1_TXENABLE_CAPTURE 0
#define FIFOED_AVALON_UART_1_TXENABLE_DATA_WIDTH 1
#define FIFOED_AVALON_UART_1_TXENABLE_DO_TEST_BENCH_WIRING 0
#define FIFOED_AVALON_UART_1_TXENABLE_DRIVEN_SIM_VALUE 0
#define FIFOED_AVALON_UART_1_TXENABLE_EDGE_TYPE "NONE"
#define FIFOED_AVALON_UART_1_TXENABLE_FREQ 50000000
#define FIFOED_AVALON_UART_1_TXENABLE_HAS_IN 0
#define FIFOED_AVALON_UART_1_TXENABLE_HAS_OUT 1
#define FIFOED_AVALON_UART_1_TXENABLE_HAS_TRI 0
#define FIFOED_AVALON_UART_1_TXENABLE_IRQ -1
#define FIFOED_AVALON_UART_1_TXENABLE_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFOED_AVALON_UART_1_TXENABLE_IRQ_TYPE "NONE"
#define FIFOED_AVALON_UART_1_TXENABLE_NAME "/dev/fifoed_avalon_uart_1_txenable"
#define FIFOED_AVALON_UART_1_TXENABLE_RESET_VALUE 0
#define FIFOED_AVALON_UART_1_TXENABLE_SPAN 16
#define FIFOED_AVALON_UART_1_TXENABLE_TYPE "altera_avalon_pio"


/*
 * hal configuration
 *
 */

#define ALT_INCLUDE_INSTRUCTION_RELATED_EXCEPTION_API
#define ALT_MAX_FD 32
#define ALT_SYS_CLK none
#define ALT_TIMESTAMP_CLK TIMER_0


/*
 * nios_activity_led_1 configuration
 *
 */

#define ALT_MODULE_CLASS_nios_activity_led_1 altera_avalon_pio
#define NIOS_ACTIVITY_LED_1_BASE 0x11080
#define NIOS_ACTIVITY_LED_1_BIT_CLEARING_EDGE_REGISTER 0
#define NIOS_ACTIVITY_LED_1_BIT_MODIFYING_OUTPUT_REGISTER 0
#define NIOS_ACTIVITY_LED_1_CAPTURE 0
#define NIOS_ACTIVITY_LED_1_DATA_WIDTH 1
#define NIOS_ACTIVITY_LED_1_DO_TEST_BENCH_WIRING 0
#define NIOS_ACTIVITY_LED_1_DRIVEN_SIM_VALUE 0
#define NIOS_ACTIVITY_LED_1_EDGE_TYPE "NONE"
#define NIOS_ACTIVITY_LED_1_FREQ 50000000
#define NIOS_ACTIVITY_LED_1_HAS_IN 0
#define NIOS_ACTIVITY_LED_1_HAS_OUT 1
#define NIOS_ACTIVITY_LED_1_HAS_TRI 0
#define NIOS_ACTIVITY_LED_1_IRQ -1
#define NIOS_ACTIVITY_LED_1_IRQ_INTERRUPT_CONTROLLER_ID -1
#define NIOS_ACTIVITY_LED_1_IRQ_TYPE "NONE"
#define NIOS_ACTIVITY_LED_1_NAME "/dev/nios_activity_led_1"
#define NIOS_ACTIVITY_LED_1_RESET_VALUE 0
#define NIOS_ACTIVITY_LED_1_SPAN 16
#define NIOS_ACTIVITY_LED_1_TYPE "altera_avalon_pio"


/*
 * onchip_memory2_1 configuration
 *
 */

#define ALT_MODULE_CLASS_onchip_memory2_1 altera_avalon_onchip_memory2
#define ONCHIP_MEMORY2_1_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY2_1_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY2_1_BASE 0x20000
#define ONCHIP_MEMORY2_1_CONTENTS_INFO ""
#define ONCHIP_MEMORY2_1_DUAL_PORT 0
#define ONCHIP_MEMORY2_1_GUI_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY2_1_INIT_CONTENTS_FILE "soc_system_onchip_memory2_1"
#define ONCHIP_MEMORY2_1_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY2_1_INSTANCE_ID "NONE"
#define ONCHIP_MEMORY2_1_IRQ -1
#define ONCHIP_MEMORY2_1_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ONCHIP_MEMORY2_1_NAME "/dev/onchip_memory2_1"
#define ONCHIP_MEMORY2_1_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY2_1_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY2_1_READ_DURING_WRITE_MODE "DONT_CARE"
#define ONCHIP_MEMORY2_1_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY2_1_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY2_1_SIZE_VALUE 49152
#define ONCHIP_MEMORY2_1_SPAN 49152
#define ONCHIP_MEMORY2_1_TYPE "altera_avalon_onchip_memory2"
#define ONCHIP_MEMORY2_1_WRITABLE 1


/*
 * timer_0 configuration
 *
 */

#define ALT_MODULE_CLASS_timer_0 altera_avalon_timer
#define TIMER_0_ALWAYS_RUN 1
#define TIMER_0_BASE 0x11000
#define TIMER_0_COUNTER_SIZE 64
#define TIMER_0_FIXED_PERIOD 0
#define TIMER_0_FREQ 50000000
#define TIMER_0_IRQ 1
#define TIMER_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define TIMER_0_LOAD_VALUE 49999
#define TIMER_0_MULT 0.001
#define TIMER_0_NAME "/dev/timer_0"
#define TIMER_0_PERIOD 1
#define TIMER_0_PERIOD_UNITS "ms"
#define TIMER_0_RESET_OUTPUT 0
#define TIMER_0_SNAPSHOT 1
#define TIMER_0_SPAN 64
#define TIMER_0_TICKS_PER_SEC 1000
#define TIMER_0_TIMEOUT_PULSE_OUTPUT 0
#define TIMER_0_TYPE "altera_avalon_timer"

#endif /* __SYSTEM_H_ */
